# My Dependatbot file ＼(^o^)／

version: 2
updates:
  - package-ecosystem: "npm"
    target-branch: "develop"
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
