# My Dependatbot file ＼(^o^)／

version: 2
updates:
  - package-ecosystem: "npm"
    target-branch: "main"
    directory: "/client"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    target-branch: "main"
    directory: "/server"
    schedule:
      interval: "monthly"
