services:
    redis:
        image: redis:latest
        container_name: redis
        restart: always
        command: ["--databases", "1"]
        healthcheck:
          test: ["CMD", "redis-cli", "ping"]
          interval: 10s
          timeout: 5s
          retries: 5
    web:
        build: .
        container_name: web
        restart: always
        ports: 
          - 8080:80
